### ISSUE TITLE
demo in plugins/slack documents maybe need fix

### ISSUE THREAD

**Issue by tgly307** [drone/drone-plugin-index#146] opened 2018-08-20 16:33 UTC
I did the test with the following example as document shows:
```
pipeline:
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/...
    channel: dev
```
but drone throw error: `Post : unsupported protocol scheme ""`
And I change drone setting as this:
```
pipeline:
  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: dev
```
and it works.
So I suspect that the document is somewhat outdated, such as webhook must be written in secrets

**Comment by tboerger** [comment] 2018-08-20 17:47
The webhook attribute should work the same way as the secret since it's both using the same internal struct mapping.

**Comment by tboerger** [comment] 2018-08-20 17:49
The webhook attribute gets translated to the env var PLUGIN WEBHOOK and the secret gets directly injected as SLACK_WEBHOOK which gets catched by https://github.com/drone-plugins/drone-slack/blob/master/main.go#L26

**Comment by bradrydzewski** [comment] 2018-08-20 18:42
👋  Hey there, the slack webhook is working for me as documented. I am going to close this as unable to reproduce (please understand we get A LOT of false positive bug reports) however, I would encourage you to send a patch to the Slack plugin repository if you are able to reproduce a bug with the existing implementation. Thanks!

**Closed by bradrydzewski** 2018-08-20 18:42 UTC
